"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";



const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const path =  usePathname();
  return (
    <html lang="en">
      <body className="bg-white">
        <div className="flex justify-between px-10 py-6 text-xl fixed top-0 left-0 w-full bg-white">
          <span className="font-bold text-2xl">lobe</span>
          <ul className="flex text-gray-400 gap-10">
        <li className={`hover:text-custom-black ${path === '/' && 'text-black'}`}>    <Link href='/' >Overview</Link>   </li>
        <li className={`hover:text-custom-black ${path === '/example' && 'text-black'}`}>    <Link href='example'>Examples</Link></li>
        <li className={`hover:text-custom-black ${path === '/tour' && 'text-black'}`}>    <Link href='tour'>Tour</Link></li>
        <li className={`hover:text-custom-black ${path === '/blog' && 'text-black'}`}>    <Link href='blog'>Blog</Link></li>
        <li className={`hover:text-custom-black ${path === '/help' && 'text-black'}`}>    <Link href='help'>Help</Link></li>
          </ul>
          <button className="flex rounded-full px-4 font-semibold text-white py-2 bg-custom-green">Download</button>
        </div>
        {children}
      </body>
    </html>
  );
}
